runtime: nodejs
env: flex

handlers:
  - url: /api/.*
    script: auto

  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html

  - url: /
    static_dir: client/build
